/* =========================================================
   LA BELLOTA CAMPERS — EXPLORA GRAN CANARIA · Lugares
   Datos de la landing /explora-gran-canaria/.
   Redacción original de La Bellota. Documentación: ver sources.md
   (fuente principal: Turismo de Gran Canaria — lugares instagrameables).
   Fotos: Wikimedia Commons con licencias libres; crédito por foto.
   ========================================================= */
window.EXPLORA_LUGARES = {
  "meta": { "version": 1, "actualizado": "2026-08-29" },

  "hero": {
    "eyebrow": "Explora Gran Canaria",
    "titulo": "Gran Canaria en camper: lugares que no te puedes perder",
    "subtitulo": "Miradores que cortan la respiración, pueblos con siglos de historia, dunas, piscinas naturales y rincones que casi nadie conoce. Todos caben en un mismo viaje si tu casa lleva ruedas.",
    "intro": "Hemos reunido los rincones más espectaculares de la isla —los mismos que recomienda Turismo de Gran Canaria— y les hemos añadido lo que nadie te cuenta: cómo llegar con una camper, dónde conviene aparcar, cuánto tiempo darle a cada sitio y en qué momento del día están en su mejor versión.",
    "cta1": "Ver lugares",
    "cta2": "Consultar disponibilidad",
    "foto": "hero-caldera.jpg",
    "credito": { "autor": "Tamara k", "lic": "CC BY-SA 3.0 ES", "url": "https://commons.wikimedia.org/wiki/File:Gran_Canaria,_Caldera_de_Tejeda,_evening.jpg" }
  },

  "categorias": [
    { "nombre": "Lugares imprescindibles", "activa": true },
    { "nombre": "Rutas en camper", "activa": false },
    { "nombre": "Playas y piscinas naturales", "activa": false },
    { "nombre": "Miradores", "activa": false },
    { "nombre": "Dónde pernoctar", "activa": false, "url": "../index.html#areas" },
    { "nombre": "Gastronomía", "activa": false }
  ],

  "lugares": [
    {
      "slug": "roque-nublo",
      "nombre": "Roque Nublo",
      "municipio": "Tejeda",
      "tag": "Símbolo de la isla",
      "destacado": true,
      "descripcion": "Hay un momento, subiendo el sendero desde La Goleta, en el que el monolito aparece de golpe entre los pinos y entiendes por qué los grancanarios lo consideran suyo. Ochenta metros de roca vertical plantados a 1.813 metros de altitud, restos de un volcán que se deshizo hace millones de años. Desde la base, el paisaje es de otro planeta: la Caldera de Tejeda a tus pies, el Bentayga enfrente y, en los días limpios, el Teide flotando sobre el mar de nubes. La caminata son unos 30–40 minutos por buen camino y merece cada paso.",
      "ideal": "Senderismo corto, fotografía de paisaje y amaneceres sobre las nubes.",
      "camper": "Se sube por la GC-600, de curvas amplias pero estrechas en tramos. El aparcadero de La Goleta es pequeño y en temporada se llena a media mañana: madruga o ve a última hora. No es zona de pernocta; para dormir cerca, los Llanos de la Pez (con permiso del Cabildo) están a unos minutos.",
      "tiempo": "2–3 horas con la caminata",
      "momento": "Amanecer o última hora de la tarde",
      "nopierdas": "La roca de la Rana, junto al Nublo, y la silueta del Teide al fondo.",
      "foto": "roque-nublo.jpg",
      "fotoAlt": "El Roque Nublo visto desde su base, en la cumbre de Gran Canaria",
      "credito": { "autor": "Basotxerri", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Roque_Nublo_24.JPG" },
      "lat": 27.970, "lng": -15.612
    },
    {
      "slug": "dunas-maspalomas",
      "nombre": "Dunas de Maspalomas",
      "municipio": "San Bartolomé de Tirajana",
      "tag": "Reserva natural",
      "destacado": true,
      "descripcion": "Un pequeño Sáhara junto al Atlántico: 400 hectáreas de arena dorada que el viento redibuja cada noche, con el faro de Maspalomas vigilando desde 1890. Es Reserva Natural Especial, así que la visita va por los senderos señalizados — y créenos, es la mejor manera: caminar descalzo por la cresta de una duna al amanecer, sin más huellas que las tuyas, es de esas cosas que no se olvidan. Al borde del sistema dunar, la Charca de Maspalomas reúne aves que paran aquí de camino a África.",
      "ideal": "Amaneceres, fotografía y caminatas descalzo por la arena.",
      "camper": "Alrededor de Maspalomas y el faro hay aparcamientos públicos señalizados; evita las horas punta y no dejes nada a la vista. La zona es urbana y transitada: aparca y muévete a pie.",
      "tiempo": "2–3 horas",
      "momento": "Amanecer, cuando la arena está intacta",
      "nopierdas": "La vista del mar de dunas desde el mirador junto al hotel Riu Palace y la charca al atardecer.",
      "foto": "dunas-maspalomas.jpg",
      "fotoAlt": "Las dunas de Maspalomas con el mar al fondo",
      "credito": { "autor": "Marc Ryckaert", "lic": "CC BY 3.0", "url": "https://commons.wikimedia.org/wiki/File:GC_Dunas_de_Maspalomas_R04.jpg" },
      "lat": 27.740, "lng": -15.586
    },
    {
      "slug": "puerto-de-mogan",
      "nombre": "Puerto de Mogán",
      "municipio": "Mogán",
      "tag": "Pueblo marinero",
      "destacado": true,
      "descripcion": "Le llaman «la pequeña Venecia» por sus canales, pero Mogán no necesita comparaciones: casas blancas rebosantes de buganvillas, un puerto donde conviven pescadores y veleros, y callejones que piden perderse sin mapa. Es el pueblo más fotogénico del suroeste y también uno de los rincones con mejor clima de la isla — aquí el sol trabaja horas extra. Al caer la tarde, cuando los turistas de excursión se marchan y la luz se vuelve naranja, el puerto recupera su ritmo tranquilo y llega su mejor momento.",
      "ideal": "Paseo, fotografía, baño en la playa del puerto y pescado fresco.",
      "camper": "La GC-200 baja hasta el pueblo con curvas cómodas. Aparca en los estacionamientos de la entrada y recorre el casco a pie (es pequeño y peatonal). Ojo: los viernes hay mercadillo y encontrar sitio se complica desde primera hora.",
      "tiempo": "2–3 horas",
      "momento": "Última hora de la tarde y puesta de sol",
      "nopierdas": "Los canales floridos entre el puerto deportivo y la playa.",
      "foto": "puerto-de-mogan.jpg",
      "fotoAlt": "El puerto deportivo de Mogán con sus casas blancas y palmeras",
      "credito": { "autor": "TimOve", "lic": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Puerto_de_Mog%C3%A1n_harbour.jpg" },
      "lat": 27.818, "lng": -15.764
    },
    {
      "slug": "mirador-del-balcon",
      "nombre": "Mirador del Balcón",
      "municipio": "La Aldea de San Nicolás",
      "tag": "Mirador",
      "destacado": true,
      "descripcion": "En el extremo oeste de la isla, una plataforma se asoma literalmente al vacío sobre un acantilado vertical. Abajo, solo Atlántico. A la derecha, la costa del Andén Verde se pierde en una sucesión de riscos en zigzag que los isleños llaman la «cola de dragón» — y cuando la ves recortada a contraluz entiendes el nombre a la primera. Es una de esas paradas que convierten una carretera en un destino: la GC-200 hasta aquí es pura película, con el mar a un lado y la montaña al otro.",
      "ideal": "Panorámicas del acantilado, fotografía y atardeceres sobre el mar.",
      "camper": "El mirador tiene un aparcamiento pequeño junto a la GC-200; con la camper es mejor llegar a primera hora o media tarde, fuera del pico de excursiones. La carretera es estrecha y sinuosa en tramos: sin prisa y usando los apartaderos para ceder paso.",
      "tiempo": "30–45 minutos de parada",
      "momento": "Atardecer, cuando el sol cae sobre el mar",
      "nopierdas": "La «cola de dragón» mirando hacia el sur desde la plataforma inferior.",
      "foto": "mirador-del-balcon.jpg",
      "fotoAlt": "La costa del Andén Verde vista desde el Mirador del Balcón",
      "credito": { "autor": "Enric", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:03_Costa_del_And%C3%A9n_Verde,_des_del_mirador_del_Balc%C3%B3n.jpg" },
      "lat": 27.980, "lng": -15.828
    },
    {
      "slug": "los-azulejos",
      "nombre": "Los Azulejos de Veneguera",
      "municipio": "Mogán · La Aldea",
      "tag": "Capricho geológico",
      "descripcion": "De pronto, en plena carretera entre Mogán y La Aldea, la montaña cambia de color: franjas verdes, turquesas, ocres y rojizas pintadas en la roca como si alguien hubiera derramado acuarelas. No es magia, es química — minerales alterados por el agua y el tiempo en una de las zonas volcánicas más antiguas de la isla —, pero el efecto es hipnótico. La luz de la mañana intensifica los verdes, y tras días de lluvia los colores parecen recién estrenados. Una parada corta que acaba llenando el carrete.",
      "ideal": "Fotografía de detalle, geología y paradas de ruta con premio.",
      "camper": "Los Azulejos se ven desde la propia GC-200; hay apartaderos pequeños junto a la carretera para detenerse un momento. Aparca solo donde quepa la camper sin invadir la vía y no cruces por curvas ciegas.",
      "tiempo": "30 minutos",
      "momento": "Por la mañana, con luz lateral",
      "nopierdas": "Los tonos turquesa junto a la Fuente de los Azulejos.",
      "foto": "los-azulejos.jpg",
      "fotoAlt": "Las franjas de colores minerales de Los Azulejos de Veneguera",
      "credito": { "autor": "Markus G. Klötzer", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Los_Azulejos_de_Veneguera_(MGK17757).jpg" },
      "lat": 27.870, "lng": -15.755
    },
    {
      "slug": "las-canteras",
      "nombre": "Playa de Las Canteras",
      "municipio": "Las Palmas de Gran Canaria",
      "tag": "Playa urbana",
      "descripcion": "Pocas capitales pueden presumir de una playa así: tres kilómetros de arena dorada atravesando la ciudad, protegidos por una barra de roca natural que convierte media playa en una piscina. En un extremo, el ambiente de barrio de La Puntilla y sus terrazas de pescado; en el otro, las olas de La Cícer, la playa de los surfistas, con el Auditorio Alfredo Kraus cerrando la escena. El paseo que la recorre entera es el salón de Las Palmas: aquí se pasea, se corre, se merienda y se ve la vida pasar.",
      "ideal": "Baño tranquilo, paseo urbano, surf y terraceo junto al mar.",
      "camper": "Es plena ciudad: lo cómodo es dejar la camper en un aparcamiento o zona habilitada y moverse a pie. Consulta las zonas de estacionamiento antes de la visita, sobre todo en verano y fines de semana.",
      "tiempo": "Medio día (combínalo con Vegueta)",
      "momento": "Atardecer junto al Auditorio",
      "nopierdas": "Un baño en marea baja sobre La Barra, cuando el mar queda plano como un lago.",
      "foto": "las-canteras.jpg",
      "fotoAlt": "La playa de Las Canteras con su paseo marítimo en Las Palmas",
      "credito": { "autor": "Nicolas Vigier", "lic": "CC0", "url": "https://commons.wikimedia.org/wiki/File:Playa_de_las_Canteras,_Las_Palmas_de_Gran_Canaria_-_51605256627.jpg" },
      "lat": 28.140, "lng": -15.432
    },
    {
      "slug": "vegueta",
      "nombre": "Vegueta",
      "municipio": "Las Palmas de Gran Canaria",
      "tag": "Casco histórico",
      "descripcion": "Aquí nació la ciudad hace más de cinco siglos, y se nota en cada esquina: calles adoquinadas, balcones canarios de madera, plazas escondidas y la mole de la Catedral de Santa Ana presidiéndolo todo. Vegueta se recorre sin plan, dejando que los callejones decidan, entre fachadas que han visto pasar conquistadores, piratas y hasta a Cristóbal Colón — su casa-museo es una de las visitas imprescindibles del barrio. Al caer la tarde, las terrazas de la zona se llenan de ambiente local.",
      "ideal": "Historia, arquitectura canaria, museos y tapeo.",
      "camper": "Como en Las Canteras: aparca en un estacionamiento de la ciudad y entra al barrio caminando — el casco es peatonal en su mayoría y no está pensado para vehículos grandes.",
      "tiempo": "2–3 horas",
      "momento": "Mañana de mercado o última hora de la tarde",
      "nopierdas": "La Casa de Colón y la vista de los balcones desde la Plaza del Pilar Nuevo.",
      "foto": "vegueta.jpg",
      "fotoAlt": "Calles del barrio histórico de Vegueta en Las Palmas de Gran Canaria",
      "credito": { "autor": "Bengt Nyman", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Vegueta_2016_02.jpg" },
      "lat": 28.100, "lng": -15.414
    },
    {
      "slug": "belen-arena",
      "nombre": "Belén de Arena de Las Canteras",
      "municipio": "Las Palmas de Gran Canaria",
      "tag": "Solo en Navidad",
      "temporada": "Diciembre – primeros de enero",
      "descripcion": "Cada diciembre, escultores de arena llegados de medio mundo levantan sobre la playa de Las Canteras un belén monumental de más de mil metros cuadrados: escenas talladas con un detalle que cuesta creer, sabiendo que todo volverá a ser playa en enero. Es una tradición muy querida en la isla — lo visitan unas 200.000 personas cada año — y una excusa perfecta para descubrir Las Palmas en Navidad, cuando la ciudad se llena de luces y el termómetro sigue marcando primavera.",
      "ideal": "Viajes en diciembre, planes en familia y fotografía nocturna.",
      "camper": "Plan urbano: aparcamiento y paseo. Si tu viaje no cae en Navidad, guárdatelo como motivo para volver — el resto del año no existe.",
      "tiempo": "1 hora (más el paseo por la playa)",
      "momento": "Al anochecer, cuando se ilumina",
      "nopierdas": "El contraste de las esculturas iluminadas con el mar de fondo.",
      "foto": null,
      "fotoNota": "Pendiente de fotografía con derechos: el belén es una obra temporal y las imágenes disponibles no permiten reutilización clara.",
      "credito": null,
      "lat": 28.145, "lng": -15.436
    },
    {
      "slug": "cesta-tejeda",
      "nombre": "La Cesta de Tejeda",
      "municipio": "Tejeda",
      "tag": "Mirador con guiño",
      "descripcion": "A la entrada de Tejeda, junto a la carretera, una cesta gigante tumbada hace de marco para una de las vistas más grandiosas de Canarias: la Caldera de Tejeda con el Roque Bentayga en el centro. La escultura homenajea la cestería tradicional, un oficio de toda la vida en las medianías, y se ha convertido en la foto obligada antes de entrar al pueblo — uno de los más bonitos de España, dicho sea de paso, con sus casas blancas, sus almendros y sus dulces que quitan el sentido.",
      "ideal": "La foto enmarcada de la caldera y una visita al pueblo con parada dulce.",
      "camper": "Está al borde de la GC-60, al límite del casco. Tejeda cuenta con aparcamientos a la entrada del pueblo; la subida es de curvas constantes, así que tómala con calma y disfruta — cada curva trae una vista nueva.",
      "tiempo": "20 minutos (+ 1–2 horas para el pueblo)",
      "momento": "Media mañana, con la caldera iluminada",
      "nopierdas": "Un bienmesabe o un mazapán de almendra en las dulcerías del pueblo.",
      "foto": "cesta-tejeda.jpg",
      "fotoAlt": "El pueblo de Tejeda con la caldera y el Roque Bentayga al fondo",
      "fotoNota": "Foto contextual del pueblo y la caldera; pendiente imagen de la escultura.",
      "credito": { "autor": "H. Zell", "lic": "CC BY-SA 3.0", "url": "https://commons.wikimedia.org/wiki/File:Tejeda,_en_Gran_Canaria_(Las_Palmas,_Espa%C3%B1a).jpg" },
      "lat": 27.996, "lng": -15.615
    },
    {
      "slug": "aguimes",
      "nombre": "Casco histórico de Agüimes",
      "municipio": "Agüimes",
      "tag": "Pueblo con encanto",
      "descripcion": "Agüimes parece la paleta de un pintor: fachadas amarillas, ocres, verdes y blancas alineadas en calles empedradas impecables, con la cúpula del templo de San Sebastián asomando sobre los tejados. El casco es un pequeño museo al aire libre — esculturas de vecinos, oficios de antaño y, sobre todo, camellos, en recuerdo de los que trabajaron estas tierras — y esconde joyas como la Casa de los Camellos, un caserón de más de trescientos años. Combinado con el vecino Barranco de Guayadeque, da para una mañana redonda.",
      "ideal": "Paseo tranquilo, arquitectura tradicional y fotografía de rincones.",
      "camper": "Aparca en los alrededores del casco (hay zonas de estacionamiento en las calles perimetrales) y entra a pie: las callejuelas del centro no son para una camper. Guayadeque está a cinco minutos en coche.",
      "tiempo": "1–2 horas",
      "momento": "Por la mañana, con el pueblo despertando",
      "nopierdas": "Las esculturas de camellos y la plaza del Rosario con el templo de fondo.",
      "foto": "aguimes.jpg",
      "fotoAlt": "El casco histórico de Agüimes coronado por el templo de San Sebastián",
      "credito": { "autor": "MarcvsDrake", "lic": "CC BY-SA 3.0 ES", "url": "https://commons.wikimedia.org/wiki/File:Vista_del_casco_hist%C3%B3rico_de_la_Villa_de_Ag%C3%BCimes_coronado_por_la_Parroquia_de_San_Sebastian.JPG" },
      "lat": 27.905, "lng": -15.446
    },
    {
      "slug": "salinas-tenefe",
      "nombre": "Salinas de Tenefé",
      "municipio": "Santa Lucía de Tirajana",
      "tag": "Patrimonio vivo",
      "descripcion": "En la punta de Tenefé, junto a Pozo Izquierdo, más de dos siglos de historia siguen funcionando a base de sol, viento y Atlántico. Las pozas se llenan de agua de mar y, al evaporarse, dejan un mosaico de tonos rosados que contrasta con la roca volcánica negra y el azul intenso de la costa este. De aquí sale una de las sales más premiadas del archipiélago — la flor de sal se recoge a mano, como siempre. Es un rincón poco transitado, de esos que se disfrutan en silencio con la cámara en la mano.",
      "ideal": "Fotografía, amaneceres y patrimonio etnográfico sin multitudes.",
      "camper": "Acceso cómodo desde la GC-1 (salida Pozo Izquierdo). Es una de las zonas más ventosas de la isla — no en vano al lado se celebra el mundial de windsurf —, así que asegura toldo y puertas. Horarios de visita y venta de sal: compruébalos antes de ir.",
      "tiempo": "45 minutos – 1 hora",
      "momento": "Amanecer, con la bruma sobre las pozas",
      "nopierdas": "Un paquete de flor de sal artesanal si encuentras el punto de venta abierto.",
      "foto": "salinas-tenefe.jpg",
      "fotoAlt": "Las pozas de las Salinas de Tenefé junto al mar",
      "credito": { "autor": "Gcdirk", "lic": "CC BY-SA 3.0 ES", "url": "https://commons.wikimedia.org/wiki/File:Salinas_de_Tenef%C3%A9_1.JPG" },
      "lat": 27.829, "lng": -15.417
    },
    {
      "slug": "mirador-unamuno",
      "nombre": "Mirador de Unamuno",
      "municipio": "Artenara",
      "tag": "Mirador",
      "descripcion": "«Una tempestad petrificada»: así describió Unamuno lo que se ve desde Artenara, y cien años después nadie lo ha contado mejor. El mirador que lleva su nombre se asoma desde el pueblo más alto de Gran Canaria a un océano de barrancos, riscos y roques — el Bentayga en primer plano, el Nublo al fondo — que al atardecer se enciende en tonos cobrizos. Artenara, además, merece calma: es tierra de casas cueva, con ermita excavada en la roca incluida, y de un silencio que ya no se encuentra fácil.",
      "ideal": "Panorámicas de la caldera, fotografía y pueblos con alma.",
      "camper": "Se llega por carreteras de cumbre estrechas y con curvas (sin dificultad especial, pero con calma). Aparca a la entrada del pueblo y muévete a pie. A esta altitud refresca incluso en verano: ten una chaqueta a mano.",
      "tiempo": "1 hora (más si visitas las casas cueva)",
      "momento": "Atardecer",
      "nopierdas": "La ermita de la Cuevita, excavada en la roca a pocos minutos del centro.",
      "foto": "mirador-unamuno.jpg",
      "fotoAlt": "La Caldera de Tejeda y el Roque Bentayga desde Artenara",
      "credito": { "autor": "Wolfgang Sauber", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Artenara_-_Ausblick_4b_Bentayga.jpg" },
      "lat": 28.020, "lng": -15.647
    },
    {
      "slug": "salinas-agaete",
      "nombre": "Piscinas naturales de Las Salinas",
      "municipio": "Agaete",
      "tag": "Baño atlántico",
      "descripcion": "En el Puerto de las Nieves, donde el malpaís se encuentra con el mar, tres piscinas de roca volcánica conectadas entre sí se llenan con cada ola. Bañarse aquí es hacerlo en pleno Atlántico pero sin sustos, con los acantilados de Tamadaba cayendo al mar de fondo y, en los días claros, el Teide dibujado en el horizonte. Después toca lo que todo el mundo hace en Agaete: pescado fresco en el puerto y paseo tranquilo hasta la punta para ver dónde estuvo el famoso Dedo de Dios.",
      "ideal": "Baño seguro en mar abierto, fotografía y atardeceres con el Teide.",
      "camper": "Hay zonas de estacionamiento en el entorno del Puerto de las Nieves; en verano y fines de semana conviene llegar temprano. El baño depende del estado del mar: si hay oleaje fuerte, mejor limítate a mirar — el Atlántico norte no perdona.",
      "tiempo": "2–3 horas con baño y paseo",
      "momento": "Tarde y puesta de sol",
      "nopierdas": "Un pescado del día en las terrazas del puerto tras el baño.",
      "foto": "salinas-agaete.jpg",
      "fotoAlt": "La costa del Puerto de las Nieves, en Agaete, junto a las piscinas naturales",
      "fotoNota": "Foto contextual del Puerto de las Nieves; pendiente imagen de las propias piscinas.",
      "credito": { "autor": "Jl FilpoC", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:El_Dedo_de_Dios_desde_el_Puerto_de_las_Nieves_(Agaete).jpg" },
      "lat": 28.100, "lng": -15.710
    },
    {
      "slug": "firgas",
      "nombre": "Casco de Firgas",
      "municipio": "Firgas",
      "tag": "La villa del agua",
      "descripcion": "Firgas suena a agua — literalmente: por el centro del pueblo baja una calle-cascada de treinta metros donde el agua corre entre bancos decorados con azulejos, en el célebre Paseo de Gran Canaria. Un poco más arriba, el Paseo de Canarias rinde homenaje a las islas con maquetas en relieve de cada una, perfectas para repasar la geografía del archipiélago con los pies en el norte verde de Gran Canaria. Es una visita corta, coqueta y diferente, ideal para combinar con la ruta de medianías del norte.",
      "ideal": "Paseo corto, azulejos, fuentes y fotografía de detalle.",
      "camper": "Pueblo pequeño de calles estrechas: aparca en las zonas de estacionamiento de las afueras del casco y baja andando. La zona norte es verde por algo — puede recibirte con llovizna: no le tengas miedo, dura poco.",
      "tiempo": "45 minutos – 1 hora",
      "momento": "Media mañana",
      "nopierdas": "Buscar tu isla favorita entre las maquetas del Paseo de Canarias.",
      "foto": "firgas.jpg",
      "fotoAlt": "El Paseo de Canarias en Firgas, con sus bancos de azulejos",
      "credito": { "autor": "Gerda Arendt", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Paseo_de_Canarias,_Firgas,_Gran_Canaria.jpg" },
      "lat": 28.107, "lng": -15.562
    },
    {
      "slug": "faro-sardina",
      "nombre": "Faro de Sardina",
      "municipio": "Gáldar",
      "tag": "Atardeceres del norte",
      "descripcion": "En la esquina noroeste de la isla, donde la costa se vuelve brava y solitaria, el faro de Punta Sardina lleva más de un siglo avisando a los barcos. No esperes multitudes: esto es el norte auténtico, de acantilados oscuros, mar rompiendo abajo y un horizonte limpio donde el sol se hunde entero en el agua — probablemente el mejor atardecer del norte grancanario. A un paso queda Sardina del Norte, un pueblito pesquero con calas de arena clara y fama justa entre los amantes del buceo.",
      "ideal": "Atardeceres, fotografía de costa brava y calas tranquilas.",
      "camper": "Se llega por carretera local desde Sardina del Norte; junto al faro el espacio para estacionar es limitado, así que en horas de puesta de sol conviene llegar con margen. El viento aquí va en serio: recoge el toldo.",
      "tiempo": "1 hora",
      "momento": "Puesta de sol",
      "nopierdas": "Un baño previo en la cala de Sardina y el chapuzón del sol desde el faro.",
      "foto": "faro-sardina.jpg",
      "fotoAlt": "El faro de Punta Sardina sobre los acantilados de Gáldar",
      "credito": { "autor": "maccanti", "lic": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Faro_nuevo_sardina_gran_canaria.jpg" },
      "lat": 28.163, "lng": -15.695
    },
    {
      "slug": "anfi",
      "nombre": "Playa de Anfi",
      "municipio": "Mogán",
      "tag": "Aguas turquesas",
      "descripcion": "Arena blanca traída del Caribe, agua turquesa amansada por un dique y una isla artificial con forma de corazón: Anfi es la playa más tropical de Gran Canaria, y no lo disimula. Protegida del viento y de las olas, es una piscina natural gigante ideal para familias, con palmeras, jardines y todos los servicios a mano. No es el rincón salvaje de la isla — para eso ya está el oeste —, pero como día de playa cómodo y fotogénico, cumple con nota.",
      "ideal": "Día de playa en familia, baño sin olas y fotos muy tropicales.",
      "camper": "Es un entorno de resort: utiliza los aparcamientos de la zona (los más próximos son de pago) y baja a pie. En temporada alta se llena pronto — mejor entre semana y a primera hora.",
      "tiempo": "Medio día",
      "momento": "Mañana, con el agua en calma",
      "nopierdas": "La vista de la isla-corazón desde el extremo del dique.",
      "foto": "anfi.jpg",
      "fotoAlt": "La playa de Anfi del Mar con su arena clara y aguas turquesas",
      "credito": { "autor": "Gfox228", "lic": "CC BY 3.0", "url": "https://commons.wikimedia.org/wiki/File:Anfi_Del_Mar_-_panoramio_(4).jpg" },
      "lat": 27.776, "lng": -15.680
    },
    {
      "slug": "santa-lucia",
      "nombre": "Casco de Santa Lucía",
      "municipio": "Santa Lucía de Tirajana",
      "tag": "Medianías del sur",
      "descripcion": "Subiendo desde el sur árido, la cuenca de Tirajana sorprende con un vergel inesperado: palmerales centenarios, huertas y, encaramado en la ladera, el casco blanco de Santa Lucía con su iglesia de cúpula roja como faro. Es la Gran Canaria rural y serena, la de las medianías, donde el tiempo va a otra velocidad. Muy cerca queda La Fortaleza, el roque donde resistieron los últimos canarios antiguos, con su centro de interpretación para entender esa historia que aún emociona.",
      "ideal": "Paisaje rural, arquitectura tradicional y arqueología canaria.",
      "camper": "La GC-65 sube desde el sur con curvas amplias y vistas crecientes. Aparca a la entrada del casco y recórrelo a pie. Si visitas La Fortaleza, comprueba antes los horarios del centro de interpretación.",
      "tiempo": "1–2 horas",
      "momento": "Media tarde, con luz cálida sobre el palmeral",
      "nopierdas": "La panorámica de la cuenca de Tirajana con el casco y las palmeras.",
      "foto": "santa-lucia.jpg",
      "fotoAlt": "La iglesia de Santa Lucía de Tirajana entre palmeras",
      "credito": { "autor": "H. Zell", "lic": "CC BY-SA 3.0", "url": "https://commons.wikimedia.org/wiki/File:Iglesia_Santa_Luc%C3%ADa_de_Tirajana.jpg" },
      "lat": 27.912, "lng": -15.540
    },
    {
      "slug": "cruz-tejeda",
      "nombre": "Cruz de Tejeda",
      "municipio": "Tejeda",
      "tag": "El cruce de la isla",
      "descripcion": "A 1.500 metros, donde históricamente se cruzaban los caminos que unían las dos vertientes de la isla, la Cruz de Tejeda sigue siendo lugar de encuentro: senderistas que arrancan ruta, puestos de quesos y dulces, burros pacientes para la foto y la terraza del Parador asomada al filo de la caldera. Cuando el alisio empuja las nubes contra la cumbre, desde aquí se ve el famoso mar de nubes lamiendo los riscos — un espectáculo que por sí solo justifica la subida.",
      "ideal": "Mar de nubes, quesos de altura y arranque de senderos.",
      "camper": "Punto de paso natural si cruzas la cumbre por la GC-15/GC-150. Hay espacio de estacionamiento en el entorno del cruce, aunque los fines de semana y festivos se anima. Por la tarde puede cerrarse la niebla: cuenta con ello al planificar la ruta.",
      "tiempo": "45 minutos – 1 hora",
      "momento": "Media mañana o última hora, según las nubes",
      "nopierdas": "Un queso curado de las medianías comprado en los puestos del cruce.",
      "foto": "cruz-tejeda.jpg",
      "fotoAlt": "La cruz de piedra del enclave de Cruz de Tejeda",
      "credito": { "autor": "Felix König", "lic": "CC BY 3.0", "url": "https://commons.wikimedia.org/wiki/File:Cruz_de_Tejeda_2010.jpg" },
      "lat": 28.010, "lng": -15.598
    },
    {
      "slug": "pozos-nieve",
      "nombre": "Mirador de los Pozos de la Nieve",
      "municipio": "Vega de San Mateo",
      "tag": "El techo de la isla",
      "descripcion": "A casi 2.000 metros, en la cumbre pelada de la isla, este mirador guarda dos sorpresas. La primera, histórica: los pozos excavados en el suelo donde durante siglos se almacenaba la nieve del invierno para vender hielo — el lujo de otra época. La segunda, monumental: una panorámica que abarca media isla, con el Roque Nublo en primera fila y, justo al lado, el Morro de la Agujereada, que con 1.956 metros es el verdadero techo de Gran Canaria. Hay hasta un marco metálico esperando tu foto.",
      "ideal": "Panorámicas totales, amaneceres sobre las nubes y fotografía.",
      "camper": "La subida a la cumbre es larga y de curvas — sin tramos difíciles, pero paciente. Aquí arriba hace frío de verdad, también en agosto al amanecer: sube abrigado. Cielo despejado casi garantizado por encima del mar de nubes.",
      "tiempo": "45 minutos",
      "momento": "Amanecer, con las nubes a tus pies",
      "nopierdas": "Encajar el Roque Nublo (y el Teide, si está claro) dentro del marco del mirador.",
      "foto": "pozos-nieve.jpg",
      "fotoAlt": "Panorámica desde la zona del Pico de las Nieves, en la cumbre de Gran Canaria",
      "credito": { "autor": "Gerda Arendt", "lic": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Pico_de_las_Nieves,_Gran_Canaria.jpg" },
      "lat": 27.962, "lng": -15.567
    }
  ],

  "faq": [
    { "p": "¿Puedo dormir con la camper en cualquiera de estos lugares?", "r": "No. En Gran Canaria pernoctar no es lo mismo que acampar, y en espacios naturales protegidos rigen normas estrictas. Lo seguro: usar las zonas de acampada del Cabildo (gratuitas, con permiso online) o los campings y áreas privadas. En nuestra sección de áreas de pernocta tienes la selección completa, y con la camper te entregamos el mapa de rincones." },
    { "p": "¿Cuántos días necesito para ver todos estos lugares?", "r": "Con 5–7 días se recorren con calma, agrupándolos por zonas: suroeste (Mogán, Azulejos, Balcón), cumbre (Nublo, Tejeda, Artenara), norte (Agaete, Sardina, Firgas) y este-capital (Las Palmas, Agüimes, Tenefé). En 3–4 días puedes hacer una buena selección. Nuestra estancia mínima son 3 noches." },
    { "p": "¿Es complicado conducir una camper por las carreteras de montaña?", "r": "La Bellota mide 6 metros y se conduce con carnet B, como una furgoneta normal. Las carreteras de cumbre (GC-60, GC-200, GC-210…) son estrechas y de curvas: la regla es ir sin prisa, usar los apartaderos para ceder paso y evitar conducir de noche por el interior. A cambio, cada curva es un mirador." },
    { "p": "¿Cuál es la mejor época para esta ruta?", "r": "Gran Canaria funciona todo el año: la costa ronda los 20–27 °C en cualquier mes. En invierno la cumbre puede bajar de 5 °C de noche (la calefacción de la camper lo resuelve) y en verano la calima puede tapar alguna panorámica. Primavera y otoño son el punto dulce: buen tiempo, buena luz y menos gente." }
  ]
};
